spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://139.199.90.88:3306/spring_cloud_db?characterEncoding=utf-8&useSSL=false
env:
  dev
